import type { NextPage } from "next";
import CardsReviewModals from "./cards-review-modals";

export type Content4Type = {
  className?: string;
};

const Content4: NextPage<Content4Type> = ({ className = "" }) => {
  return (
    <div
      className={`self-stretch overflow-hidden flex flex-col items-center justify-center relative gap-6 text-left text-lg text-color-tokens-content-dark-primary font-body-extra-large-semibold ${className}`}
    >
      <div className="overflow-hidden flex flex-row items-start justify-start gap-6 z-[0]">
        <CardsReviewModals
          variant={3}
          starsNew="/starsnew.svg"
          coolCryptoCurrencyFastWithdra="Since implementing this CRM, our sales have increased by 30% in just three months. It's become an integral part of our growth strategy."
          testimonialPerson="/testimonial-person@2x.png"
          abelSheldon="Marx Hershey"
          entrepreneur="Project Manager"
        />
        <CardsReviewModals
          variant={3}
          starsNew="/starsnew.svg"
          starsNewIconMargin="unset"
          starsNewMargin="unset"
          coolCryptoCurrencyFastWithdra="This CRM has transformed how we interact with our customers. The marketing automation and customer insights have been game-changers for us. Highly recommended!"
          coolCryptoCurrencyDisplay="-webkit-inline-box"
          coolCryptoCurrencyWebkitLineClamp="unset"
          coolCryptoCurrencyWebkitBoxOrient="unset"
          coolCryptoCurrencyHeight="unset"
          testimonialPerson="/testimonial-person-1@2x.png"
          abelSheldon="Tyra Dhillon"
          entrepreneur="Software Tester"
        />
        <CardsReviewModals
          variant={3}
          starsNew="/starsnew.svg"
          starsNewIconMargin="unset"
          starsNewMargin="unset"
          coolCryptoCurrencyFastWithdra="I was looking for a CRM that was easy to use and could adapt to my business. This CRM has exceeded my expectations. It's simple, intuitive, and customizable."
          coolCryptoCurrencyDisplay="-webkit-inline-box"
          coolCryptoCurrencyWebkitLineClamp="unset"
          coolCryptoCurrencyWebkitBoxOrient="unset"
          coolCryptoCurrencyHeight="unset"
          testimonialPerson="/testimonial-person1@2x.png"
          abelSheldon="Courtney Henry"
          entrepreneur="UI/UX Designer"
        />
        <CardsReviewModals
          variant={3}
          starsNew="/starsnew.svg"
          starsNewIconMargin="unset"
          starsNewMargin="unset"
          coolCryptoCurrencyFastWithdra="The sales pipeline and automation tools have been a massive time-saver. We can now manage leads and deals more efficiently, which has had a direct impact on our bottom line."
          coolCryptoCurrencyDisplay="inline-block"
          coolCryptoCurrencyWebkitLineClamp="unset"
          coolCryptoCurrencyWebkitBoxOrient="unset"
          coolCryptoCurrencyHeight="100px"
          testimonialPerson="/testimonial-person2@2x.png"
          abelSheldon="Marvin McKinney"
          entrepreneur="Team Leader"
        />
      </div>
      <div className="overflow-hidden flex flex-row items-start justify-start gap-6 z-[1]">
        <CardsReviewModals
          variant={3}
          starsNew="/starsnew.svg"
          starsNewIconMargin="unset"
          starsNewMargin="unset"
          coolCryptoCurrencyFastWithdra="The reports generated by this CRM have allowed us to track and measure our performance better than ever. It's helped us identify areas for improvement and growth opportunities."
          coolCryptoCurrencyDisplay="-webkit-inline-box"
          coolCryptoCurrencyWebkitLineClamp="unset"
          coolCryptoCurrencyWebkitBoxOrient="unset"
          coolCryptoCurrencyHeight="unset"
          testimonialPerson="/testimonial-person-4@2x.png"
          abelSheldon="Roselle Ehrman"
          entrepreneur="Software Developer"
        />
        <CardsReviewModals
          variant={3}
          starsNew="/starsnew.svg"
          starsNewIconMargin="unset"
          starsNewMargin="unset"
          coolCryptoCurrencyFastWithdra="The ability to segment customers and personalize our marketing campaigns has led to a significant increase in conversion rates. It's been a game-changer for our e-commerce business."
          coolCryptoCurrencyDisplay="-webkit-inline-box"
          coolCryptoCurrencyWebkitLineClamp="unset"
          coolCryptoCurrencyWebkitBoxOrient="unset"
          coolCryptoCurrencyHeight="unset"
          testimonialPerson="/testimonial-person1@2x.png"
          abelSheldon="Floyd Miles"
          entrepreneur="Software Development Manager"
        />
        <CardsReviewModals
          variant={3}
          starsNew="/starsnew.svg"
          starsNewIconMargin="unset"
          starsNewMargin="unset"
          coolCryptoCurrencyFastWithdra="Our customer support has become more organized and efficient with this CRM. The ticketing system and knowledge base features have made a significant difference in how we serve our customers."
          coolCryptoCurrencyDisplay="-webkit-inline-box"
          coolCryptoCurrencyWebkitLineClamp="unset"
          coolCryptoCurrencyWebkitBoxOrient="unset"
          coolCryptoCurrencyHeight="unset"
          testimonialPerson="/testimonial-person2@2x.png"
          abelSheldon="Lauralee Quintero"
          entrepreneur="Scrum Master"
        />
        <CardsReviewModals
          variant={3}
          starsNew="/starsnew.svg"
          starsNewIconMargin="unset"
          starsNewMargin="unset"
          coolCryptoCurrencyFastWithdra="The collaboration features in this CRM have greatly improved how our teams work together. Sharing information and coordinating has never been easier."
          coolCryptoCurrencyDisplay="-webkit-inline-box"
          coolCryptoCurrencyWebkitLineClamp="unset"
          coolCryptoCurrencyWebkitBoxOrient="unset"
          coolCryptoCurrencyHeight="unset"
          testimonialPerson="/testimonial-person-1@2x.png"
          abelSheldon="Kylee Danford"
          entrepreneur="Ethical Hacker"
        />
        <CardsReviewModals
          variant={3}
          starsNewIconMargin="0"
          starsNewMargin="unset"
          coolCryptoCurrencyFastWithdra="This CRM seamlessly integrated with our existing systems. The implementation was a breeze, and it's made a significant difference in our data management."
          coolCryptoCurrencyDisplay="-webkit-inline-box"
          coolCryptoCurrencyWebkitLineClamp="unset"
          coolCryptoCurrencyWebkitBoxOrient="unset"
          coolCryptoCurrencyHeight="unset"
          testimonialPerson="/testimonial-person3@2x.png"
          abelSheldon="Dianne Russell"
          entrepreneur="Scrum Master"
        />
      </div>
      <div className="overflow-hidden flex flex-row items-start justify-start gap-6 z-[2]">
        <CardsReviewModals
          variant={3}
          starsNew="/starsnew.svg"
          starsNewIconMargin="unset"
          starsNewMargin="0"
          coolCryptoCurrencyFastWithdra="This CRM has transformed how we interact with our customers. The marketing automation and customer insights have been game-changers for us. Highly recommended!"
          coolCryptoCurrencyDisplay="-webkit-inline-box"
          coolCryptoCurrencyWebkitLineClamp="unset"
          coolCryptoCurrencyWebkitBoxOrient="unset"
          coolCryptoCurrencyHeight="unset"
          testimonialPerson="/testimonial-person-9@2x.png"
          abelSheldon="Tyra Dhillon"
          entrepreneur="Software Tester"
        />
        <CardsReviewModals
          variant={3}
          starsNew="/starsnew.svg"
          starsNewIconMargin="unset"
          starsNewMargin="unset"
          coolCryptoCurrencyFastWithdra="Since implementing this CRM, our sales have increased by 30% in just three months. It's become an integral part of our growth strategy."
          coolCryptoCurrencyDisplay="-webkit-inline-box"
          coolCryptoCurrencyWebkitLineClamp="unset"
          coolCryptoCurrencyWebkitBoxOrient="unset"
          coolCryptoCurrencyHeight="unset"
          testimonialPerson="/testimonial-person-1@2x.png"
          abelSheldon="Marx Hershey"
          entrepreneur="Project Manager"
        />
        <CardsReviewModals
          variant={3}
          starsNew="/starsnew.svg"
          starsNewIconMargin="unset"
          starsNewMargin="unset"
          coolCryptoCurrencyFastWithdra="The sales pipeline and automation tools have been a massive time-saver. We can now manage leads and deals more efficiently, which has had a direct impact on our bottom line."
          coolCryptoCurrencyDisplay="inline-block"
          coolCryptoCurrencyWebkitLineClamp="unset"
          coolCryptoCurrencyWebkitBoxOrient="unset"
          coolCryptoCurrencyHeight="100px"
          testimonialPerson="/testimonial-person1@2x.png"
          abelSheldon="Marvin McKinney"
          entrepreneur="Team Leader"
        />
        <CardsReviewModals
          variant={3}
          starsNew="/starsnew.svg"
          starsNewIconMargin="unset"
          starsNewMargin="unset"
          coolCryptoCurrencyFastWithdra="The reports generated by this CRM have allowed us to track and measure our performance better than ever. It's helped us identify areas for improvement and growth opportunities."
          coolCryptoCurrencyDisplay="-webkit-inline-box"
          coolCryptoCurrencyWebkitLineClamp="unset"
          coolCryptoCurrencyWebkitBoxOrient="unset"
          coolCryptoCurrencyHeight="unset"
          testimonialPerson="/testimonial-person2@2x.png"
          abelSheldon="Roselle Ehrman"
          entrepreneur="Software Developer"
        />
      </div>
      <div className="w-[928px] absolute !m-[0] top-[calc(50%_-_464px)] left-[calc(50%_+_640px)] [background:linear-gradient(0deg,_#fff,_rgba(255,_255,_255,_0)_18.75%,_rgba(255,_255,_255,_0)_86.26%,_#fff)] h-[1280px] [transform:_rotate(90deg)] [transform-origin:0_0] z-[3]" />
    </div>
  );
};

export default Content4;
